### ISSUE TITLE
University of Glasgow logo PDF not included in repository

### ISSUE THREAD

**Issue by SeanDS** [transientlunatic/glasgow-theme#1]
I get the error:

```
LaTeX Warning: File `UoG_keyline.pdf' not found on input line 21.

! Unable to load picture or PDF file 'UoG_keyline.pdf'.
```

when running `make`. There does not appear to be this PDF bundled with the repository files.

**Comment by transientlunatic** [comment]
This was fixed in commit eb96b54 by adding a script to pull the image into the downloaded repository. To avoid copyright problems the logos aren't distributed in the repository.
